In [7]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [10]:
def item1():
    return np.array([i for i in range(1, 11)], dtype=int)
print(item1())

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [11]:
def item2():
    return np.zeros((3,3), dtype=int)
print(item2())

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [14]:
def item3():
    return np.random.randint(1, 10 + 1, size=(5,5))
print(item3())

[[10  4  7  8  6]
 [10  7  9  5  6]
 [ 7  4 10  9  4]
 [ 5  6  9  3  6]
 [ 5  4  2  8  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [16]:
def item4():
    return np.random.rand(4,4)
print(item4())

[[0.85210719 0.47104428 0.87262275 0.96213009]
 [0.1942365  0.44624632 0.33989872 0.24784737]
 [0.02946743 0.42143502 0.29871719 0.33446948]
 [0.92863611 0.20951859 0.56691074 0.76035757]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте
на них поелементні операції додавання, віднімання та множення.

In [20]:
def item5():
    array1 = np.random.randint(1, 11, size=(5, 5))  
    array2 = np.random.randint(1, 11, size=(5, 5))  
    return (f'array1 = \n{array1}\n\n'
            f'array2 = \n{array2}\n\n'
            f'array1 + array2 = \n{array1 + array2}\n\n'
            f'array1 - array2 = \n{array1 - array2}\n\n'
            f'array1 * array2 = \n{array1 * array2}')
print(item5())

array1 = 
[[ 1  9  9  7  9]
 [10  7  1 10  8]
 [ 1  7  6  2  5]
 [10  1  7  1  8]
 [ 2  6 10  6 10]]

array2 = 
[[ 1  1 10  4 10]
 [ 1  5  5  6  2]
 [ 5  2 10  7  5]
 [ 9  9  5  5  7]
 [ 8  3 10  9  3]]

array1 + array2 = 
[[ 2 10 19 11 19]
 [11 12  6 16 10]
 [ 6  9 16  9 10]
 [19 10 12  6 15]
 [10  9 20 15 13]]

array1 - array2 = 
[[ 0  8 -1  3 -1]
 [ 9  2 -4  4  6]
 [-4  5 -4 -5  0]
 [ 1 -8  2 -4  1]
 [-6  3  0 -3  7]]

array1 * array2 = 
[[  1   9  90  28  90]
 [ 10  35   5  60  16]
 [  5  14  60  14  25]
 [ 90   9  35   5  56]
 [ 16  18 100  54  30]]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [21]:
def item6():
    v1 = np.array([i for i in range(1,8)], dtype=int)
    v2 = np.array([i for i in range(1,8)], dtype=int)
    return v1, v2, np.dot(v1, v1)
print(item6())

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 3, 4, 5, 6, 7]), 140)


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [24]:
def item7():
    array1 = np.random.randint(1, 11, size=(2, 2))
    array2 = np.random.randint(1, 11, size=(2, 3))
    return array1, array2, array1 @ array2
print(item7())

(array([[2, 6],
       [2, 8]]), array([[ 4,  7,  4],
       [10,  5,  3]]), array([[68, 44, 26],
       [88, 54, 32]]))


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [31]:
def item8():
    array = np.random.randint(1, 11, size=(3, 3))
    if np.linalg.det(array) != 0:
        return array, np.linalg.inv(array)
    else: 
        return array
print(item8())

(array([[ 1,  2,  7],
       [ 2,  3,  2],
       [ 6,  5, 10]]), array([[-0.38461538, -0.28846154,  0.32692308],
       [ 0.15384615,  0.61538462, -0.23076923],
       [ 0.15384615, -0.13461538,  0.01923077]]))


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [32]:
def item9():
    array = np.random.rand(4,4)
    return array, array.T
print(item9())

(array([[0.69919417, 0.3217303 , 0.90305334, 0.84753505],
       [0.92148592, 0.34400956, 0.71539808, 0.74567965],
       [0.74074192, 0.72539913, 0.26660386, 0.93991108],
       [0.62443419, 0.35814353, 0.26735623, 0.20520271]]), array([[0.69919417, 0.92148592, 0.74074192, 0.62443419],
       [0.3217303 , 0.34400956, 0.72539913, 0.35814353],
       [0.90305334, 0.71539808, 0.26660386, 0.26735623],
       [0.84753505, 0.74567965, 0.93991108, 0.20520271]]))


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [35]:
def item10():
    array = np.random.randint(1, 11, size=(3, 4))
    vector = np.random.randint(1, 11, size=(4, 1))
    return array, vector, array @ vector # повинні отримати вектор 3х1
print(item10())

(array([[ 3,  1,  4,  4],
       [ 6, 10,  7,  9],
       [ 4,  7,  4,  6]]), array([[ 7],
       [ 8],
       [ 3],
       [10]]), array([[ 81],
       [233],
       [156]]))


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [36]:
def item11():
    array = np.random.rand(2, 3)
    vector = np.random.rand(3)
    return array, vector, array @ vector # 2x3 and 3x1 -> 2x1
print(item11())

(array([[0.17219862, 0.87333152, 0.32432435],
       [0.83884762, 0.31260751, 0.45639398]]), array([0.9674121 , 0.77567262, 0.26954361]), array([0.93142594, 1.1770105 ]))


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [38]:
def item12():
    array1 = np.random.randint(1, 11, size=(2, 2))
    array2 = np.random.randint(1, 11, size=(2, 2))
    return array1, array2, array1 * array2
print(item12())

(array([[ 3,  4],
       [10,  6]]), array([[9, 4],
       [4, 6]]), array([[27, 16],
       [40, 36]]))


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
def item13():
    array1 = np.random.randint(1, 11, size=(2, 2))
    array2 = np.random.randint(1, 11, size=(2, 2))
    return array1, array2, array1 @ array2
print(item13())

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [39]:
def item14():
    array = np.random.randint(1, 101, size=(5, 5))
    return array, np.sum(array)
print(item14())

(array([[27, 29, 93, 38,  6],
       [14, 10,  8, 15, 33],
       [20, 38, 42, 52, 52],
       [47, 82, 29, 84,  3],
       [61, 27,  5, 99,  6]]), 920)


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [40]:
def item15():
    array1 = np.random.randint(1, 11, size=(4, 4))
    array2 = np.random.randint(1, 11, size=(4, 4))
    return array1, array2, array1 - array2
print(item15())

(array([[ 6,  9,  9,  7],
       [ 7,  8,  5,  2],
       [ 6,  5,  2,  3],
       [ 2,  5, 10, 10]]), array([[6, 5, 9, 4],
       [8, 7, 1, 2],
       [1, 5, 6, 2],
       [8, 6, 8, 4]]), array([[ 0,  4,  0,  3],
       [-1,  1,  4,  0],
       [ 5,  0, -4,  1],
       [-6, -1,  2,  6]]))


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
що містить суму елементів кожного рядка матриці.

In [42]:
def item16():
    array = np.random.rand(3, 3)
    row_sums = np.sum(array, axis=1)
    column_vector = row_sums[:, np.newaxis]
    return array, column_vector
print(item16())

(array([[0.18741962, 0.96771884, 0.43286672],
       [0.6795831 , 0.31170395, 0.57899834],
       [0.8103755 , 0.31883879, 0.36762055]]), array([[1.58800517],
       [1.57028539],
       [1.49683485]]))


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [44]:
def item17():
    array = np.random.randint(1, 11, size=(3,4))
    return array, array ** 2
print(item17())

(array([[2, 9, 7, 7],
       [6, 1, 6, 8],
       [6, 5, 8, 2]]), array([[ 4, 81, 49, 49],
       [36,  1, 36, 64],
       [36, 25, 64,  4]]))


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [45]:
def item18():
    vector = np.random.randint(1, 51, size=(4))
    return vector, vector ** 0.5
print(item18())

(array([39, 13, 49, 35]), array([6.244998  , 3.60555128, 7.        , 5.91607978]))
